INSERT INTO direcciones (direccion_calle_numero,direccion_ciudad,direccion_provincia,direccion_pais)
VALUES
  ("769-1938 Purus Av.","Lewiston","Wisconsin","Argentina"),
  ("654-642 Et Rd.","Kapolei","Arkansas","Argentina"),
  ("5107 Dapibus Ave","Augusta","Utah","Argentina"),
  ("P.O. Box 817, 4723 Sem, Rd.","Tallahassee","Kentucky","Argentina"),
  ("Ap #846-1231 Sed Road","Missoula","Maryland","Argentina"),
  ("441-2411 Sapien Rd.","Pocatello","Arkansas","Argentina"),
  ("300-6079 Auctor, Avenue","South Portland","Montana","Argentina"),
  ("459-617 Quis Street","Little Rock","Hawaii","Argentina"),
  ("Ap #325-8552 Dictum. Rd.","Pocatello","Colorado","Argentina"),
  ("Ap #106-1740 In Av.","Fairbanks","Pennsylvania","Argentina"),
  ("Ap #588-1580 Nunc Road","Rochester","Washington","Argentina"),
  ("P.O. Box 889, 8149 Duis St.","South Portland","Mississippi","Argentina"),
  ("2940 Donec Street","South Burlington","Maryland","Argentina"),
  ("922-6810 Sed Ave","Independence","Montana","Argentina"),
  ("774-893 Ultrices. Av.","Springfield","Wisconsin","Argentina"),
  ("801-4492 Pede. Av.","Seattle","Connecticut","Argentina"),
  ("P.O. Box 803, 395 Arcu Ave","Lafayette","Tennessee","Argentina"),
  ("P.O. Box 925, 2275 Faucibus Av.","Columbia","Maryland","Argentina"),
  ("8045 Non Avenue","Henderson","Alabama","Argentina"),
  ("Ap #975-4649 Imperdiet, Rd.","Montpelier","Alaska","Argentina"),
  ("P.O. Box 583, 3659 Quis St.","South Bend","Kansas","Argentina"),
  ("515-5774 Feugiat St.","Biloxi","Arizona","Argentina"),
  ("324-5032 Faucibus St.","College","Maryland","Argentina"),
  ("770-6285 Vitae Ave","Huntsville","Colorado","Argentina"),
  ("Ap #373-2052 Phasellus Street","Akron","Utah","Argentina"),
  ("P.O. Box 291, 254 Vulputate Avenue","Gillette","Kentucky","Argentina"),
  ("Ap #158-4779 Vitae St.","Kapolei","Indiana","Argentina"),
  ("5108 Integer St.","Sterling Heights","Colorado","Argentina"),
  ("546-5603 Pellentesque Av.","Provo","Washington","Argentina"),
  ("669-512 Sed St.","Billings","Arizona","Argentina"),
  ("459-4007 Sem St.","Annapolis","California","Argentina"),
  ("P.O. Box 909, 3204 Duis Rd.","Kaneohe","Missouri","Argentina"),
  ("903-882 Auctor Rd.","South Burlington","Pennsylvania","Argentina"),
  ("536-2448 At, St.","Burlington","Connecticut","Argentina"),
  ("Ap #485-9465 Nisi Road","New Orleans","Michigan","Argentina"),
  ("2033 Ut, St.","Little Rock","Michigan","Argentina"),
  ("472-3319 Leo, St.","Lakewood","Virginia","Argentina"),
  ("2429 Purus. Avenue","Auburn","Vermont","Argentina"),
  ("745-137 Risus. Ave","Meridian","Maine","Argentina"),
  ("7439 Phasellus Rd.","Tuscaloosa","Ohio","Argentina"),
  ("725-7871 Aliquet Rd.","Columbus","Hawaii","Argentina"),
  ("Ap #296-9583 Sem Avenue","Kaneohe","Tennessee","Argentina"),
  ("P.O. Box 345, 3677 Nullam Rd.","Minneapolis","Wisconsin","Argentina"),
  ("P.O. Box 624, 6514 Nulla Road","Fort Wayne","Alabama","Argentina"),
  ("851-364 Elit, Rd.","South Burlington","Illinois","Argentina"),
  ("440-576 Facilisis Av.","Kearney","Indiana","Argentina"),
  ("7502 Luctus Street","Auburn","Tennessee","Argentina"),
  ("952-7269 In, Avenue","Columbus","Alaska","Argentina"),
  ("872 Tortor Road","Rock Springs","Kentucky","Argentina"),
  ("P.O. Box 451, 7840 Nec Road","Pittsburgh","Hawaii","Argentina");
INSERT INTO direcciones (direccion_calle_numero,direccion_ciudad,direccion_provincia,direccion_pais)
VALUES
  ("665-2323 Quis St.","Knoxville","Mississippi","Argentina"),
  ("Ap #549-9429 Ante St.","Owensboro","Colorado","Argentina"),
  ("Ap #500-3110 Pede. St.","Bowling Green","California","Argentina"),
  ("Ap #308-3696 Aenean St.","Salt Lake City","Oklahoma","Argentina"),
  ("258-3557 Et Street","Lewiston","Pennsylvania","Argentina"),
  ("P.O. Box 891, 4741 Dui. Avenue","Stamford","Michigan","Argentina"),
  ("Ap #835-5842 Curabitur Ave","Baton Rouge","Oklahoma","Argentina"),
  ("6605 Urna, Road","Bozeman","Kansas","Argentina"),
  ("Ap #974-9326 Enim Rd.","Covington","Wisconsin","Argentina"),
  ("P.O. Box 254, 4653 Amet, Street","West Valley City","Kansas","Argentina"),
  ("670 Aenean Avenue","Idaho Falls","Pennsylvania","Argentina"),
  ("P.O. Box 587, 2801 Velit. St.","Gillette","Maryland","Argentina"),
  ("787-3033 Quis St.","Cincinnati","Oklahoma","Argentina"),
  ("943-3992 Purus, Rd.","Sandy","Hawaii","Argentina"),
  ("P.O. Box 691, 5117 Ut Rd.","Iowa City","Pennsylvania","Argentina"),
  ("Ap #861-9737 Etiam Rd.","Chattanooga","Oklahoma","Argentina"),
  ("Ap #778-8118 Fringilla St.","Hattiesburg","Tennessee","Argentina"),
  ("635-2580 Eget, Av.","Columbia","Michigan","Argentina"),
  ("7788 Nullam Rd.","Baltimore","Delaware","Argentina"),
  ("784-9686 Est, Av.","Aurora","Utah","Argentina"),
  ("573-6215 Facilisis Road","Cambridge","Tennessee","Argentina"),
  ("357-4147 Lacus Av.","Newark","Kentucky","Argentina"),
  ("704-8323 Elit Ave","Racine","Kentucky","Argentina"),
  ("Ap #533-6866 Vitae Street","Cleveland","Arkansas","Argentina"),
  ("Ap #472-5907 Mi St.","Frankfort","Indiana","Argentina"),
  ("Ap #698-1543 Nunc Av.","Lincoln","Idaho","Argentina"),
  ("7885 Mauris St.","Duluth","Indiana","Argentina"),
  ("9063 Vivamus Road","Richmond","Massachusetts","Argentina"),
  ("P.O. Box 180, 6476 Semper Street","Annapolis","Florida","Argentina"),
  ("790-6144 Ipsum St.","West Jordan","Colorado","Argentina"),
  ("Ap #350-5185 Nulla Rd.","South Bend","Maine","Argentina"),
  ("475-8622 Litora Road","Newark","Oklahoma","Argentina"),
  ("P.O. Box 274, 8949 Nulla Avenue","Lexington","Louisiana","Argentina"),
  ("Ap #497-1872 Augue Rd.","Shreveport","Colorado","Argentina"),
  ("7661 Consequat, Road","Birmingham","Minnesota","Argentina"),
  ("312-7754 Tempor, St.","Little Rock","Kentucky","Argentina"),
  ("Ap #452-8291 A St.","Sandy","Alabama","Argentina"),
  ("P.O. Box 214, 7754 Turpis Av.","Annapolis","Colorado","Argentina"),
  ("Ap #696-897 Non Rd.","Essex","Oklahoma","Argentina"),
  ("458-8336 Tempor St.","Warren","Vermont","Argentina"),
  ("757-9156 Volutpat Rd.","Dallas","Virginia","Argentina"),
  ("Ap #390-4778 Vivamus Rd.","Overland Park","Vermont","Argentina"),
  ("403-9660 Sed Ave","Anchorage","Ohio","Argentina"),
  ("Ap #511-5301 Aliquam St.","Chandler","Washington","Argentina"),
  ("272-3480 Elit St.","Great Falls","Wisconsin","Argentina"),
  ("882-1176 Lacinia St.","Portland","Kansas","Argentina"),
  ("P.O. Box 616, 8835 Non, Rd.","Joliet","Mississippi","Argentina"),
  ("Ap #161-2637 Ut Road","Columbus","Wisconsin","Argentina"),
  ("Ap #115-964 Dui St.","Bellevue","Wyoming","Argentina"),
  ("6507 Mi. Ave","Fort Smith","Texas","Argentina");
INSERT INTO direcciones (direccion_calle_numero,direccion_ciudad,direccion_provincia,direccion_pais)
VALUES
  ("832 Lectus. Av.","Idaho Falls","Nevada","Argentina"),
  ("Ap #957-5608 Placerat Avenue","Portland","Wisconsin","Argentina"),
  ("4158 Dolor St.","Jackson","Arizona","Argentina"),
  ("P.O. Box 701, 2124 Sed, Ave","Fairbanks","Tennessee","Argentina"),
  ("357-169 A Ave","Mobile","Vermont","Argentina"),
  ("8984 Et, Road","Stamford","Wisconsin","Argentina"),
  ("Ap #483-530 Vitae, Av.","Detroit","Alaska","Argentina"),
  ("Ap #583-9591 Arcu. Rd.","Hartford","Minnesota","Argentina"),
  ("976-1436 Pellentesque Rd.","Houston","California","Argentina"),
  ("537-6111 Massa. Road","Henderson","Louisiana","Argentina"),
  ("539-2033 Massa. Street","Rochester","Missouri","Argentina"),
  ("Ap #665-3899 Tristique Avenue","Bloomington","Tennessee","Argentina"),
  ("Ap #884-4513 Rhoncus. Rd.","Pocatello","Wisconsin","Argentina"),
  ("497-2329 Vestibulum Rd.","Grand Rapids","Louisiana","Argentina"),
  ("4973 Vitae Avenue","Broken Arrow","Nevada","Argentina"),
  ("308-5269 Sodales Street","Fayetteville","Idaho","Argentina"),
  ("P.O. Box 491, 9682 Pharetra Ave","New Haven","Connecticut","Argentina"),
  ("790-8809 Gravida Road","Denver","Hawaii","Argentina"),
  ("P.O. Box 831, 8885 Elit Street","Independence","Michigan","Argentina"),
  ("Ap #165-4332 Arcu. St.","Chicago","Arkansas","Argentina"),
  ("Ap #359-4602 Ridiculus Ave","Harrisburg","Nevada","Argentina"),
  ("Ap #542-2243 Vitae, Road","Nampa","Wyoming","Argentina"),
  ("Ap #462-8305 Libero Avenue","Kenosha","Vermont","Argentina"),
  ("Ap #934-9068 Consectetuer, St.","Athens","Vermont","Argentina"),
  ("897-9862 Arcu. Street","Racine","Texas","Argentina"),
  ("P.O. Box 553, 8110 Pretium Street","Tulsa","Idaho","Argentina"),
  ("6305 Fermentum Rd.","Sterling Heights","Hawaii","Argentina"),
  ("Ap #236-589 Pretium Ave","Columbus","Maine","Argentina"),
  ("977-3396 Sit Rd.","Metairie","Tennessee","Argentina"),
  ("P.O. Box 700, 4418 Lorem Avenue","San Francisco","Virginia","Argentina"),
  ("196-6999 Parturient Street","Montpelier","Wyoming","Argentina"),
  ("6048 Lobortis St.","Reading","Hawaii","Argentina"),
  ("Ap #282-7998 Nunc Rd.","Gresham","Missouri","Argentina"),
  ("P.O. Box 159, 8307 Nulla Avenue","Annapolis","Arkansas","Argentina"),
  ("Ap #852-3356 Adipiscing Av.","Springfield","Michigan","Argentina"),
  ("840-8679 Vel Avenue","St. Petersburg","Idaho","Argentina"),
  ("P.O. Box 769, 866 Dolor Street","Portland","Nebraska","Argentina"),
  ("Ap #565-9653 Iaculis Road","Ketchikan","Ohio","Argentina"),
  ("605-4265 Etiam Rd.","Jefferson City","Michigan","Argentina"),
  ("381-1409 Nec St.","Burlington","Alaska","Argentina"),
  ("Ap #563-3427 Bibendum St.","Stamford","Oklahoma","Argentina"),
  ("173-5402 Auctor Rd.","Reading","Michigan","Argentina"),
  ("Ap #818-3940 Adipiscing Rd.","Cincinnati","Kentucky","Argentina"),
  ("434-3746 Vel St.","Reading","Alaska","Argentina"),
  ("Ap #517-6422 Libero. St.","Bowling Green","Illinois","Argentina"),
  ("Ap #153-8265 Est St.","Waterbury","Arizona","Argentina"),
  ("786-463 Leo. Avenue","Jonesboro","Washington","Argentina"),
  ("Ap #575-1986 Dictum Avenue","Sterling Heights","Louisiana","Argentina"),
  ("Ap #711-8442 Magna. Av.","Fort Wayne","Massachusetts","Argentina"),
  ("930-3644 Consequat Avenue","Davenport","Maryland","Argentina");
INSERT INTO direcciones (direccion_calle_numero,direccion_ciudad,direccion_provincia,direccion_pais)
VALUES
  ("P.O. Box 777, 5874 Senectus Avenue","Spokane","Kansas","Argentina"),
  ("765-674 Mauris Road","Norman","Michigan","Argentina"),
  ("Ap #570-2246 Quis, Avenue","Columbus","Maine","Argentina"),
  ("294-2314 Sociis Av.","Columbus","Illinois","Argentina"),
  ("5471 Feugiat. Rd.","Naperville","Colorado","Argentina"),
  ("Ap #254-8987 Vitae Street","Biloxi","Arkansas","Argentina"),
  ("Ap #407-7681 Nec, Av.","Clarksville","Indiana","Argentina"),
  ("Ap #773-9910 Odio. Rd.","Tucson","Oklahoma","Argentina"),
  ("Ap #834-8102 Dui, Ave","Kailua","Oregon","Argentina"),
  ("Ap #507-6220 Faucibus St.","Helena","Georgia","Argentina"),
  ("557-8470 Ante. Street","Portland","Missouri","Argentina"),
  ("700-4398 Mi St.","Bangor","Arizona","Argentina"),
  ("Ap #238-9154 Ultricies Street","Gulfport","Arkansas","Argentina"),
  ("149-2833 Magnis Ave","Augusta","Indiana","Argentina"),
  ("Ap #164-1008 Velit. Av.","Wyoming","Mississippi","Argentina"),
  ("Ap #631-5722 Nulla Rd.","Hillsboro","Kentucky","Argentina"),
  ("417-8320 Libero Road","West Jordan","Virginia","Argentina"),
  ("P.O. Box 760, 4480 Eu Ave","Vancouver","Delaware","Argentina"),
  ("4823 Eu St.","Olympia","Wyoming","Argentina"),
  ("279-1627 Nonummy. Avenue","Houston","Wisconsin","Argentina"),
  ("Ap #563-7468 Malesuada St.","San Diego","Pennsylvania","Argentina"),
  ("305-1646 Sagittis St.","Warren","Washington","Argentina"),
  ("Ap #805-3008 Parturient St.","Gillette","Ohio","Argentina"),
  ("188-3303 Convallis Rd.","Metairie","Maine","Argentina"),
  ("286-9709 Malesuada Road","Lafayette","Colorado","Argentina"),
  ("2375 Eros. St.","Virginia Beach","Oklahoma","Argentina"),
  ("Ap #627-7207 Aliquet. St.","Warren","Idaho","Argentina"),
  ("703-3797 Nisi. Rd.","Orlando","Indiana","Argentina"),
  ("Ap #550-2653 Hendrerit Rd.","Pike Creek","Idaho","Argentina"),
  ("P.O. Box 968, 8688 Sit St.","Colchester","Wyoming","Argentina"),
  ("4849 Molestie Road","Grand Island","Montana","Argentina"),
  ("Ap #196-6576 Lorem, St.","Green Bay","Georgia","Argentina"),
  ("471-3023 Accumsan Road","Fairbanks","Montana","Argentina"),
  ("939-5621 Sit St.","Indianapolis","Florida","Argentina"),
  ("Ap #796-8576 Phasellus Avenue","Virginia Beach","Mississippi","Argentina"),
  ("194-6283 Arcu. Street","Phoenix","Michigan","Argentina"),
  ("369-8457 Placerat Avenue","Montpelier","California","Argentina"),
  ("Ap #654-5981 Orci. Rd.","Kapolei","Indiana","Argentina"),
  ("3277 Malesuada Ave","Chesapeake","Maryland","Argentina"),
  ("746-6439 Morbi Av.","Columbus","Louisiana","Argentina"),
  ("P.O. Box 427, 3623 Diam. Avenue","Warren","Wisconsin","Argentina"),
  ("P.O. Box 783, 4438 Eu, Rd.","Hattiesburg","Maine","Argentina"),
  ("790-5896 Tellus. Avenue","Duluth","California","Argentina"),
  ("Ap #311-7348 Dictum Road","North Las Vegas","Mississippi","Argentina"),
  ("P.O. Box 329, 7022 Purus Ave","Clarksville","Vermont","Argentina"),
  ("P.O. Box 927, 3928 A, Road","Reading","Delaware","Argentina"),
  ("Ap #101-8438 Facilisis St.","Bridgeport","Florida","Argentina"),
  ("Ap #955-5636 Cursus Ave","Great Falls","Maryland","Argentina"),
  ("Ap #953-9402 Sit St.","Fresno","Tennessee","Argentina"),
  ("Ap #367-3263 Vel St.","Lansing","Maryland","Argentina");
INSERT INTO direcciones (direccion_calle_numero,direccion_ciudad,direccion_provincia,direccion_pais)
VALUES
  ("P.O. Box 819, 3109 Malesuada Rd.","Milwaukee","Alaska","Argentina"),
  ("P.O. Box 260, 5855 Neque Rd.","West Valley City","Massachusetts","Argentina"),
  ("Ap #202-3395 Felis Street","Pittsburgh","Illinois","Argentina"),
  ("P.O. Box 279, 7026 Id, Avenue","Aurora","Mississippi","Argentina"),
  ("P.O. Box 782, 4241 Est Avenue","Portland","Illinois","Argentina"),
  ("P.O. Box 789, 6873 Sagittis Ave","Baltimore","Alaska","Argentina"),
  ("694-4743 Nunc. Rd.","Topeka","Texas","Argentina"),
  ("260-4838 Aliquam Road","Richmond","Arizona","Argentina"),
  ("Ap #138-5703 Metus Ave","Columbia","Nevada","Argentina"),
  ("P.O. Box 449, 3344 Odio Ave","Sandy","Pennsylvania","Argentina"),
  ("1272 Sem Avenue","North Las Vegas","Wyoming","Argentina"),
  ("Ap #407-2672 Sed, Rd.","Jackson","Iowa","Argentina"),
  ("621-7646 Vitae, St.","Henderson","Maine","Argentina"),
  ("713-4294 Morbi Rd.","Jonesboro","Iowa","Argentina"),
  ("Ap #373-9233 Fusce St.","Warren","Kentucky","Argentina"),
  ("Ap #250-5178 Erat Street","Fort Collins","Washington","Argentina"),
  ("Ap #532-7997 Etiam St.","Burlington","Hawaii","Argentina"),
  ("2859 Nullam Road","Kenosha","Nevada","Argentina"),
  ("711-5171 Tellus Rd.","Kapolei","Wisconsin","Argentina"),
  ("7369 Tristique Ave","Chandler","Ohio","Argentina"),
  ("6451 Eu, Avenue","Detroit","Alabama","Argentina"),
  ("9540 Aliquam Ave","Portland","Oregon","Argentina"),
  ("Ap #849-537 Erat. St.","Gillette","Delaware","Argentina"),
  ("Ap #146-9875 Ipsum. Rd.","Lakewood","Iowa","Argentina"),
  ("P.O. Box 755, 6146 Placerat. Rd.","Reno","Maine","Argentina"),
  ("8243 Tincidunt. St.","San Jose","Washington","Argentina"),
  ("Ap #478-5392 Dis Road","Annapolis","Texas","Argentina"),
  ("Ap #217-5007 Magna. St.","Colchester","Alabama","Argentina"),
  ("P.O. Box 750, 839 Feugiat. Avenue","Provo","Arkansas","Argentina"),
  ("997-1042 Eget Rd.","Vancouver","Nebraska","Argentina"),
  ("910-7315 In Rd.","Rockford","Arkansas","Argentina"),
  ("490-6292 Augue Av.","Nashville","Delaware","Argentina"),
  ("524-6117 Mi Street","West Valley City","Missouri","Argentina"),
  ("Ap #665-500 Sed Av.","Pocatello","Indiana","Argentina"),
  ("745-8049 Quis, Road","Warren","Iowa","Argentina"),
  ("Ap #876-6658 Faucibus Street","Norfolk","Kansas","Argentina"),
  ("Ap #885-7863 Enim. St.","Bellevue","Mississippi","Argentina"),
  ("Ap #726-7370 Posuere Rd.","Augusta","Minnesota","Argentina"),
  ("826-5161 Nisl. Ave","South Portland","Minnesota","Argentina"),
  ("5743 Erat Street","Ketchikan","Ohio","Argentina"),
  ("6141 Duis Road","Topeka","Georgia","Argentina"),
  ("117-1625 Lobortis Rd.","Lafayette","Texas","Argentina"),
  ("9143 Penatibus Rd.","Kapolei","Delaware","Argentina"),
  ("Ap #415-939 Ridiculus Rd.","Casper","Vermont","Argentina"),
  ("155-7380 Eget Road","Des Moines","Oklahoma","Argentina"),
  ("Ap #883-9436 Odio. St.","Frankfort","Idaho","Argentina"),
  ("Ap #339-5278 Vulputate, Rd.","Sterling Heights","Alabama","Argentina"),
  ("Ap #230-9156 Elit. Rd.","Atlanta","Kentucky","Argentina"),
  ("Ap #202-6697 Pellentesque Rd.","Las Vegas","Delaware","Argentina"),
  ("Ap #223-9256 Penatibus Ave","Montpelier","Montana","Argentina");
INSERT INTO direcciones (direccion_calle_numero,direccion_ciudad,direccion_provincia,direccion_pais)
VALUES
  ("6899 Duis St.","Aurora","Oklahoma","Argentina"),
  ("Ap #414-8891 Curabitur St.","Austin","Wyoming","Argentina"),
  ("Ap #380-5279 Ultrices Road","Louisville","Louisiana","Argentina"),
  ("Ap #529-3033 Augue Av.","Duluth","Kansas","Argentina"),
  ("Ap #826-3011 Luctus St.","Biloxi","Mississippi","Argentina"),
  ("945-5692 Lorem, Ave","Aurora","Mississippi","Argentina"),
  ("P.O. Box 354, 6604 At Av.","Jefferson City","Nevada","Argentina"),
  ("914 Nec, St.","Norfolk","Oregon","Argentina"),
  ("3303 Libero Road","Reno","Florida","Argentina"),
  ("P.O. Box 572, 2123 A, Road","Springfield","Virginia","Argentina"),
  ("218-3978 Vivamus Street","Reading","Arizona","Argentina"),
  ("Ap #991-432 Donec Rd.","Paradise","Massachusetts","Argentina"),
  ("Ap #278-752 Vitae Rd.","New Haven","California","Argentina"),
  ("P.O. Box 257, 2218 Nisl Road","Auburn","Maryland","Argentina"),
  ("574-435 Est, Road","Fort Worth","Ohio","Argentina"),
  ("1133 Per Street","Kapolei","Louisiana","Argentina"),
  ("P.O. Box 227, 4028 Cras Rd.","Henderson","Alaska","Argentina"),
  ("848-4824 Eget, Rd.","Southaven","Michigan","Argentina"),
  ("Ap #172-5305 Et Rd.","Augusta","Michigan","Argentina"),
  ("P.O. Box 386, 2097 Phasellus St.","Tallahassee","Minnesota","Argentina"),
  ("P.O. Box 489, 9273 Dolor Road","Hilo","Oklahoma","Argentina"),
  ("Ap #412-9377 Libero. St.","Chattanooga","Wyoming","Argentina"),
  ("780-1783 Ipsum Street","Annapolis","Tennessee","Argentina"),
  ("Ap #131-9543 Dolor St.","Gulfport","Hawaii","Argentina"),
  ("543-1593 Imperdiet, Avenue","Sacramento","Arizona","Argentina"),
  ("6623 Proin Ave","Boise","Utah","Argentina"),
  ("P.O. Box 972, 145 Torquent St.","Seattle","Arizona","Argentina"),
  ("647-2484 Est, Road","Springfield","Iowa","Argentina"),
  ("P.O. Box 321, 6004 Augue Street","Evansville","Arizona","Argentina"),
  ("7776 Erat Av.","Tuscaloosa","Idaho","Argentina"),
  ("Ap #555-7370 Vel Road","New Haven","Colorado","Argentina"),
  ("1257 Dolor Avenue","Mobile","Georgia","Argentina"),
  ("Ap #599-6278 Ac Rd.","Lafayette","Tennessee","Argentina"),
  ("6385 Nulla St.","Olympia","Maryland","Argentina"),
  ("405-7207 Accumsan Street","Casper","Utah","Argentina"),
  ("5067 Taciti Av.","Hattiesburg","Arkansas","Argentina"),
  ("Ap #288-4269 Vestibulum St.","Wyoming","Montana","Argentina"),
  ("225-7726 Et Rd.","Anchorage","Wisconsin","Argentina"),
  ("3984 Eu Ave","Mobile","Nebraska","Argentina"),
  ("Ap #377-4242 Tincidunt. Street","Chicago","Florida","Argentina"),
  ("Ap #381-1262 Erat St.","Fresno","Indiana","Argentina"),
  ("Ap #652-3540 Placerat, St.","Great Falls","Maryland","Argentina"),
  ("9992 Odio. Street","Owensboro","Georgia","Argentina"),
  ("6030 Nunc Ave","Newark","Wyoming","Argentina"),
  ("Ap #519-3450 Varius Av.","Miami","Texas","Argentina"),
  ("213-9177 Aliquet Avenue","Bozeman","Maine","Argentina"),
  ("P.O. Box 286, 2950 Convallis Road","Burlington","Louisiana","Argentina"),
  ("Ap #737-3987 Nec Av.","Saint Louis","Montana","Argentina"),
  ("Ap #666-5548 Ut St.","Sacramento","Georgia","Argentina"),
  ("Ap #113-4655 Sed Road","Oklahoma City","Connecticut","Argentina");
INSERT INTO direcciones (direccion_calle_numero,direccion_ciudad,direccion_provincia,direccion_pais)
VALUES
  ("2074 Blandit Road","Fairbanks","Missouri","Argentina"),
  ("594-6506 Taciti Rd.","Tacoma","Indiana","Argentina"),
  ("8835 Et Avenue","Chesapeake","Wyoming","Argentina"),
  ("3807 Euismod Avenue","Auburn","Arizona","Argentina"),
  ("Ap #336-2314 Commodo Ave","Aurora","Oregon","Argentina"),
  ("Ap #841-1242 Egestas, Road","Jonesboro","Oregon","Argentina"),
  ("3552 Tempor St.","Pittsburgh","Pennsylvania","Argentina"),
  ("795-733 Accumsan Road","Kansas City","Wyoming","Argentina"),
  ("911-6101 Cras St.","Akron","Indiana","Argentina"),
  ("P.O. Box 803, 6420 Aliquet Street","Fort Wayne","Washington","Argentina"),
  ("Ap #324-342 Elementum, Road","Des Moines","Colorado","Argentina"),
  ("Ap #997-1504 Turpis. St.","Columbus","Georgia","Argentina"),
  ("518-7408 Proin Road","Dover","Arkansas","Argentina"),
  ("P.O. Box 157, 519 Eleifend, Avenue","Butte","Pennsylvania","Argentina"),
  ("P.O. Box 439, 4778 Faucibus St.","Chesapeake","Wyoming","Argentina"),
  ("353-2450 Lacinia St.","West Valley City","Wyoming","Argentina"),
  ("Ap #349-9879 Et Street","Jacksonville","Virginia","Argentina"),
  ("Ap #751-3691 Risus. St.","Fresno","Louisiana","Argentina"),
  ("P.O. Box 180, 7474 Ligula. Rd.","Wilmington","Pennsylvania","Argentina"),
  ("P.O. Box 782, 4003 Venenatis Rd.","Columbus","Arkansas","Argentina"),
  ("P.O. Box 852, 6725 Elit Av.","Cambridge","Texas","Argentina"),
  ("P.O. Box 144, 2083 Magnis Rd.","Iowa City","Delaware","Argentina"),
  ("Ap #472-9350 Purus. Street","Mesa","Illinois","Argentina"),
  ("Ap #977-4545 Placerat. Avenue","Stamford","Montana","Argentina"),
  ("358-1764 Ante Street","Casper","Montana","Argentina"),
  ("P.O. Box 713, 497 Neque. Road","Tallahassee","Oklahoma","Argentina"),
  ("5984 Odio Av.","Louisville","Wyoming","Argentina"),
  ("Ap #214-3847 Aliquam Av.","Wyoming","Wyoming","Argentina"),
  ("665-3895 Vivamus St.","Frankfort","Arizona","Argentina"),
  ("P.O. Box 663, 463 Nulla Ave","Norfolk","Kentucky","Argentina"),
  ("6803 Nulla Ave","Orlando","Illinois","Argentina"),
  ("1184 Scelerisque Av.","Akron","Wyoming","Argentina"),
  ("6375 Vitae St.","Salt Lake City","Indiana","Argentina"),
  ("Ap #352-4605 Tellus. Rd.","Wilmington","Illinois","Argentina"),
  ("989-4585 Integer St.","North Las Vegas","Iowa","Argentina"),
  ("P.O. Box 128, 373 Enim Ave","Idaho Falls","Wisconsin","Argentina"),
  ("148-3872 Eu Ave","Lincoln","Oklahoma","Argentina"),
  ("1281 In Rd.","Missoula","Oregon","Argentina"),
  ("Ap #791-1684 Euismod Street","Gary","Minnesota","Argentina"),
  ("426-2399 Malesuada Ave","West Valley City","Ohio","Argentina"),
  ("Ap #980-6320 Egestas St.","Green Bay","Mississippi","Argentina"),
  ("546-4150 Morbi St.","Grand Island","Michigan","Argentina"),
  ("P.O. Box 596, 1635 Dictum Street","Des Moines","Washington","Argentina"),
  ("8982 Nascetur St.","New Haven","Michigan","Argentina"),
  ("Ap #130-9703 Lobortis Rd.","Kansas City","Georgia","Argentina"),
  ("717-3915 Enim, Street","Boston","Pennsylvania","Argentina"),
  ("2755 Lacinia. Rd.","Fort Wayne","Indiana","Argentina"),
  ("Ap #936-9556 Suspendisse Rd.","Rutland","Florida","Argentina"),
  ("1084 Penatibus St.","Springfield","Tennessee","Argentina"),
  ("273-9484 Ut Ave","Chandler","Nevada","Argentina");
INSERT INTO direcciones (direccion_calle_numero,direccion_ciudad,direccion_provincia,direccion_pais)
VALUES
  ("Ap #783-7239 Et Street","Columbus","Kansas","Argentina"),
  ("P.O. Box 451, 2808 At Street","Lincoln","Alabama","Argentina"),
  ("Ap #777-169 Posuere Street","Covington","Arkansas","Argentina"),
  ("8144 At, Av.","Carson City","Wyoming","Argentina"),
  ("P.O. Box 725, 2185 Sodales Rd.","Baton Rouge","Alaska","Argentina"),
  ("Ap #251-1431 Velit Avenue","Aurora","California","Argentina"),
  ("2333 A Rd.","Kaneohe","Ohio","Argentina"),
  ("405-9003 Iaculis Avenue","Portland","Wisconsin","Argentina"),
  ("Ap #935-407 Ipsum Avenue","Henderson","Mississippi","Argentina"),
  ("280-6311 Cras Road","Duluth","Idaho","Argentina"),
  ("588-8975 Consectetuer Av.","Minneapolis","Nebraska","Argentina"),
  ("Ap #530-1248 Libero Avenue","Sacramento","Minnesota","Argentina"),
  ("8294 Mi, Ave","Little Rock","Wisconsin","Argentina"),
  ("3294 Cursus Street","Bloomington","Arkansas","Argentina"),
  ("9781 Sociis Road","Owensboro","Washington","Argentina"),
  ("913-588 Blandit Avenue","Harrisburg","Ohio","Argentina"),
  ("P.O. Box 346, 7873 Ullamcorper. Avenue","Kansas City","Vermont","Argentina"),
  ("Ap #396-9520 Id Av.","Des Moines","Arizona","Argentina"),
  ("316-8966 Mollis Rd.","Covington","Colorado","Argentina"),
  ("P.O. Box 978, 8626 Dolor St.","New Orleans","Delaware","Argentina"),
  ("P.O. Box 218, 1829 Gravida Av.","Owensboro","Alabama","Argentina"),
  ("480-9984 Luctus Street","Auburn","Wyoming","Argentina"),
  ("Ap #304-2498 Nunc Av.","Orlando","Maryland","Argentina"),
  ("P.O. Box 195, 1652 Urna Rd.","Fayetteville","Missouri","Argentina"),
  ("308-7425 Conubia St.","Knoxville","Montana","Argentina"),
  ("7184 Magna. Ave","Tampa","Maine","Argentina"),
  ("978-370 Nam Road","Minneapolis","Texas","Argentina"),
  ("P.O. Box 300, 5088 Massa. Ave","Kapolei","Arkansas","Argentina"),
  ("Ap #689-7527 Vel, Rd.","Fort Smith","Indiana","Argentina"),
  ("506-4088 Semper Road","Bellevue","Massachusetts","Argentina"),
  ("142-6933 Et Rd.","Boston","Kentucky","Argentina"),
  ("Ap #968-859 In Rd.","Spokane","Nebraska","Argentina"),
  ("136-7208 Adipiscing, Av.","Bloomington","Tennessee","Argentina"),
  ("867-8350 Sit St.","Austin","Missouri","Argentina"),
  ("736-1891 Felis, Av.","Reading","Nevada","Argentina"),
  ("733-905 Egestas Ave","Akron","Pennsylvania","Argentina"),
  ("P.O. Box 413, 5623 Sollicitudin Avenue","Columbia","Illinois","Argentina"),
  ("169-8798 Ultrices. Road","Bridgeport","Alabama","Argentina"),
  ("199-8356 Mauris. Avenue","New Haven","Indiana","Argentina"),
  ("Ap #506-2685 Senectus Rd.","Akron","Arizona","Argentina"),
  ("782-1852 Primis Ave","Metairie","Florida","Argentina"),
  ("9542 Orci, Avenue","Allentown","Colorado","Argentina"),
  ("P.O. Box 594, 643 Erat, Road","Wilmington","Maryland","Argentina"),
  ("P.O. Box 451, 7456 Sed Ave","Savannah","Oklahoma","Argentina"),
  ("Ap #172-7532 Montes, Street","San Antonio","Kentucky","Argentina"),
  ("183-4085 Nullam Street","Philadelphia","Texas","Argentina"),
  ("361-8232 Nunc Ave","Georgia","Kentucky","Argentina"),
  ("Ap #961-2413 Vitae, St.","Knoxville","Minnesota","Argentina"),
  ("Ap #726-4331 Sed Avenue","Omaha","Mississippi","Argentina"),
  ("944-9800 Vitae Street","Bloomington","Kentucky","Argentina");
INSERT INTO direcciones (direccion_calle_numero,direccion_ciudad,direccion_provincia,direccion_pais)
VALUES
  ("588-7834 Ante St.","Carson City","Ohio","Argentina"),
  ("856-2110 Nunc Ave","Fort Wayne","Connecticut","Argentina"),
  ("881-5139 Libero Street","Davenport","Iowa","Argentina"),
  ("Ap #380-398 Integer Rd.","Rochester","Oklahoma","Argentina"),
  ("P.O. Box 293, 7495 Cum St.","Rutland","Arkansas","Argentina"),
  ("Ap #510-251 Turpis Street","Philadelphia","Maine","Argentina"),
  ("P.O. Box 685, 8815 Mauris, Ave","Bloomington","Arizona","Argentina"),
  ("P.O. Box 504, 8239 Consectetuer Av.","Baton Rouge","Alabama","Argentina"),
  ("3400 Sapien Street","Cincinnati","Kansas","Argentina"),
  ("Ap #229-2594 Consectetuer Ave","Oklahoma City","Arizona","Argentina"),
  ("3306 Ac Street","Casper","Utah","Argentina"),
  ("Ap #188-8662 Id, St.","Laramie","Iowa","Argentina"),
  ("809-3802 Sed Av.","Montpelier","Iowa","Argentina"),
  ("Ap #663-6606 Velit. St.","Chicago","Kansas","Argentina"),
  ("821-3267 Nam St.","Augusta","California","Argentina"),
  ("P.O. Box 308, 8373 Vehicula. Rd.","Mesa","Maine","Argentina"),
  ("2623 Donec St.","Boise","Nevada","Argentina"),
  ("628-3631 Sapien, Avenue","Iowa City","California","Argentina"),
  ("7605 Nam Ave","West Jordan","Minnesota","Argentina"),
  ("157-5364 Sagittis. Rd.","Norfolk","Idaho","Argentina"),
  ("707-5082 Diam Av.","Rutland","Louisiana","Argentina"),
  ("104-8982 Nec Street","Mobile","Minnesota","Argentina"),
  ("292-9860 Eget, St.","Mobile","Wisconsin","Argentina"),
  ("770-8511 Accumsan Rd.","Phoenix","Arkansas","Argentina"),
  ("140-5721 Mattis Ave","Frankfort","Texas","Argentina"),
  ("Ap #806-7520 Lorem Avenue","Olympia","Maryland","Argentina"),
  ("6193 Porta St.","Vancouver","Pennsylvania","Argentina"),
  ("129-2746 Montes, Road","Columbus","Alabama","Argentina"),
  ("951-461 Interdum Ave","Norman","Idaho","Argentina"),
  ("P.O. Box 574, 350 Nam Street","Jacksonville","Maryland","Argentina"),
  ("289-8533 Duis Street","Atlanta","Wyoming","Argentina"),
  ("Ap #956-783 Consectetuer St.","Hillsboro","Virginia","Argentina"),
  ("P.O. Box 397, 9519 Faucibus St.","Des Moines","Minnesota","Argentina"),
  ("Ap #946-7357 Purus. Rd.","Gillette","Alaska","Argentina"),
  ("Ap #793-2322 Nulla Av.","Kaneohe","Indiana","Argentina"),
  ("Ap #350-805 Pede. Road","Tucson","Louisiana","Argentina"),
  ("P.O. Box 913, 9190 Egestas St.","Georgia","Ohio","Argentina"),
  ("P.O. Box 201, 3677 Ante. Street","Hartford","Connecticut","Argentina"),
  ("Ap #600-2940 Non Road","Waterbury","Hawaii","Argentina"),
  ("8482 Ut Avenue","Broken Arrow","Texas","Argentina"),
  ("P.O. Box 415, 1899 Sed Ave","Sacramento","Minnesota","Argentina"),
  ("Ap #353-1851 Enim. Street","Hartford","Wyoming","Argentina"),
  ("760-852 Feugiat. Ave","South Bend","Ohio","Argentina"),
  ("536-8245 Duis Road","Ketchikan","Kansas","Argentina"),
  ("Ap #862-7417 Nunc Road","Provo","Ohio","Argentina"),
  ("1843 Et Rd.","St. Petersburg","Tennessee","Argentina"),
  ("P.O. Box 943, 3225 Mi Av.","Gillette","California","Argentina"),
  ("135-9670 Donec Street","Covington","Tennessee","Argentina"),
  ("141-2048 Orci Street","Norfolk","Oregon","Argentina"),
  ("Ap #330-3645 Semper St.","Cambridge","Utah","Argentina");
INSERT INTO direcciones (direccion_calle_numero,direccion_ciudad,direccion_provincia,direccion_pais)
VALUES
  ("563-598 Pellentesque, Rd.","Little Rock","Kansas","Argentina"),
  ("P.O. Box 290, 2606 Feugiat. Street","Columbus","Kentucky","Argentina"),
  ("8888 Non Rd.","Fort Wayne","Wisconsin","Argentina"),
  ("5625 Enim Street","Fayetteville","Texas","Argentina"),
  ("P.O. Box 533, 6148 Enim, St.","Olathe","Iowa","Argentina"),
  ("Ap #979-9366 Auctor Street","New Haven","Nevada","Argentina"),
  ("P.O. Box 632, 483 Ac Ave","Cleveland","Delaware","Argentina"),
  ("Ap #497-5081 Imperdiet, Rd.","Fort Worth","Utah","Argentina"),
  ("Ap #558-4511 Arcu. Rd.","Bangor","Nebraska","Argentina"),
  ("832-1631 Placerat. St.","Reading","Virginia","Argentina"),
  ("P.O. Box 815, 4439 Mauris Ave","Omaha","Pennsylvania","Argentina"),
  ("Ap #838-9526 Sed St.","Portland","Montana","Argentina"),
  ("4602 Nascetur Ave","Clarksville","Michigan","Argentina"),
  ("P.O. Box 571, 9518 Mauris Rd.","Casper","Kentucky","Argentina"),
  ("Ap #446-8819 Mauris Avenue","Fresno","Louisiana","Argentina"),
  ("P.O. Box 262, 5850 Elementum St.","Overland Park","Maine","Argentina"),
  ("Ap #197-9439 Erat, St.","South Burlington","Georgia","Argentina"),
  ("Ap #104-917 Vitae Av.","Fayetteville","Michigan","Argentina"),
  ("456-1832 Parturient Ave","Nashville","Wyoming","Argentina"),
  ("Ap #763-8306 Justo Ave","Virginia Beach","Arizona","Argentina"),
  ("P.O. Box 389, 2012 Dictum. Ave","Auburn","Oklahoma","Argentina"),
  ("P.O. Box 826, 6334 Dictum St.","Seattle","Delaware","Argentina"),
  ("Ap #176-7951 Mi, Av.","Aurora","Pennsylvania","Argentina"),
  ("432-8676 Vitae, Rd.","Akron","Colorado","Argentina"),
  ("944-4963 Sed, St.","Norfolk","Vermont","Argentina"),
  ("802 Nunc Rd.","Akron","Oklahoma","Argentina"),
  ("405-6091 Ridiculus St.","Springfield","Utah","Argentina"),
  ("P.O. Box 434, 5285 Vestibulum, Rd.","Hattiesburg","Oregon","Argentina"),
  ("Ap #899-7086 Donec Street","New Haven","Illinois","Argentina"),
  ("P.O. Box 320, 9284 Vestibulum Av.","Richmond","Mississippi","Argentina"),
  ("660-7337 Dignissim. Avenue","Boise","Alaska","Argentina"),
  ("Ap #941-1210 Nec, Rd.","Butte","Arkansas","Argentina"),
  ("P.O. Box 933, 9961 Erat. Rd.","Erie","Washington","Argentina"),
  ("Ap #762-7955 Elementum, Av.","Baton Rouge","Montana","Argentina"),
  ("719-6116 Facilisis Ave","Vancouver","Colorado","Argentina"),
  ("Ap #489-5413 Eu, St.","Fort Worth","Missouri","Argentina"),
  ("3529 Est Avenue","Birmingham","Wyoming","Argentina"),
  ("2519 Iaculis, Rd.","Kapolei","Alabama","Argentina"),
  ("9661 Ultrices Avenue","Sterling Heights","Maine","Argentina"),
  ("971-1117 Dictum Ave","Fort Worth","Colorado","Argentina"),
  ("Ap #739-5813 Nunc Rd.","Hattiesburg","Alaska","Argentina"),
  ("Ap #770-1418 Tellus St.","Laramie","Illinois","Argentina"),
  ("P.O. Box 729, 4239 Nisi St.","Kenosha","Tennessee","Argentina"),
  ("493-9278 Phasellus Rd.","Athens","Illinois","Argentina"),
  ("304-8563 Tristique St.","Knoxville","Hawaii","Argentina"),
  ("731-6734 Et Street","Columbus","Alaska","Argentina"),
  ("P.O. Box 226, 5134 Eget, St.","Fort Worth","Utah","Argentina"),
  ("900-1298 Non Avenue","Evansville","Wisconsin","Argentina"),
  ("Ap #527-3803 Dolor Street","Baltimore","Massachusetts","Argentina"),
  ("P.O. Box 768, 1995 Curabitur Rd.","Little Rock","California","Argentina");
